### ISSUE TITLE
Problem compiling qmqtt-client

### ISSUE THREAD

**Issue by krimp** [emqtt/qmqtt-client#8]
According to the link given in the readme, the qmqtt library to use with qmqtt-client is https://github.com/emqtt/qmqtt. It seems to me like qmqtt-client is based on an old version of qmqtt, and will not compile using the qmqtt in the link given in the readme.

**Comment by wuming123057** [comment]
Yes. This version corresponds to the version [qmqtt v0.1 version](https://github.com/emqtt/qmqtt/releases)
The new version of qmqtt is testing.
We are on this basis to modify this version, please wait.

**Comment by wuming123057** [comment]
Now you can download the test.
The master repo  corresponds to  the qmqtt library.
